### ISSUE TITLE
extent ?

### ISSUE THREAD

**Issue by Fil** [Fil/d3-tricontour#1]
Ease the creation of tricontours that extend beyond the hull, by adding "fake" points along a path. Maybe this should be just a few examples, with:
- four corners
- many points along a rectangle
- many points along a circle.

**Comment by hobbspauldevon94** [comment]
Yep no clue wat yor talkin about

**Comment by Fil** [comment]
an example is given here https://observablehq.com/@fil/manhattan-voronoi-cells-osmnx
