### ISSUE TITLE
Is it possible to get isolines?

### ISSUE THREAD

**Issue by ssquirrel** [Fil/d3-tricontour#12]
First off, thank you very much for this amazing library!

I was trying to highlight isolines and add labels to them just like what you did in this example https://observablehq.com/@fil/contour-labels-svg. Is there a way to get isolines easily? Thanks again.

**Comment by Fil** [comment]
All the contours are isolines; here's an example https://observablehq.com/@fil/tricontour-labels

![chart](https://user-images.githubusercontent.com/7001/171995217-1c6d752a-09a4-400c-b690-bc1e1a503d64.png)
