### ISSUE TITLE
Edge Polygons Misaligned by a Small Margin

### ISSUE THREAD

**Issue by zachsa** [Fil/d3-tricontour#15]
I've been using the `d3-contour` library, and  want to switch back to the `d3-tricontour library`. I notice that the the polygons around the edge are not quite as well aligned in `d3-tricontour` as they are in `d3-contour`. Is this possible/easy to fix?

_**d3-contour polygon edges**_

![image](https://user-images.githubusercontent.com/6336500/236835149-498d0d3a-9acc-46bf-8643-f0e06129aff4.png)

_**dr-tricontour polygon edges**_

![image](https://user-images.githubusercontent.com/6336500/236835340-a5a0b407-fa85-43d2-851c-ec6e41462504.png)

**Comment by Fil** [comment]
Can you share the example as an observable notebook?

**Comment by Fil** [comment]
closing due to lack of information
