### ISSUE TITLE
Calculating aspects and slopes/gradients of triangle surfaces

### ISSUE THREAD

**Issue by osper66** [Fil/d3-tricontour#6]
Any plan or idea for this?

Thanks for advance.

**Comment by Fil** [comment]
I'm sorry I dont understand the question. But I'm curious—do you have an example?

**Comment by osper66** [comment]
About aspects and gradients described in following(page 9-13).

 http://www.fresnostate.edu/csm/ees/documents/facstaff/wang/gis200/lecture-notes/gis/chap13.pdf 

 ArcGIS Pro and QGIS(https://docs.qgis.org/2.14/en/docs/training_manual/rasters/terrain_analysis.html)
 has terrain analysis function including these.

**Comment by osper66** [comment]
I found more detail illustrated description in https://www.onestopgis.com/GIS-Theory-and-Techniques/Terrain-Mapping-and-Analysis/Terrain-Analysis-Slope-and-Aspect/2-Approx-Methods-for-Calculating-Slope-Aspect.html

**Comment by Fil** [comment]
Right, but this would be related to the triangulation, not the contours?

It should be relatively easy to compute :
- the normal to triangle ABC is the cross-product AB x AC, normalized to 1 (*x*, *y*, *z*)
- the slope's cosine is the vertical component of the normal (*z*)
- the aspect is atan2(*y*, *x*)

Let me know if you have a concrete dataset that would benefit from this.
